# Generated by Django 5.0.2 on 2024-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_userlocal_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='details',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='UserLocal',
        ),
    ]
