# Generated by Django 5.0.2 on 2024-03-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_categorycourse_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
