# Generated by Django 5.0.3 on 2024-03-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
