# Generated by Django 5.0.3 on 2024-03-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_rename_customer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
