# Generated by Django 5.0.3 on 2024-03-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_customer_user_instructor_course_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderCourses',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
