# Generated by Django 5.0.3 on 2024-03-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_remove_customer_name_remove_instructor_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercourses',
            old_name='order_items',
            new_name='order',
        ),
    ]
