# Generated by Django 5.0.6 on 2024-05-24 16:50

import academy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_coursesrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blogs_imgs/'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='courses_imgs/'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='customers_imgs/'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='image',
            field=models.ImageField(null=True, upload_to='documentations_imgs/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(null=True, upload_to='instructors_imgs/'),
        ),
        migrations.CreateModel(
            name='CoursesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=academy.models.get_upload_path)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_imgs', to='academy.blog')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_imgs', to='academy.course')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_imgs', to='academy.customer')),
                ('documentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_imgs', to='academy.documentation')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_imgs', to='academy.instructor')),
            ],
        ),
    ]
