# Generated by Django 5.0.6 on 2024-05-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_blog_image_course_image_course_slug_customer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycourse',
            name='image',
            field=models.ImageField(null=True, upload_to='categorycourse_imgs/'),
        ),
        migrations.AddField(
            model_name='coursesimages',
            name='categorycourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorycourse_imgs', to='academy.categorycourse'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_imgs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='customer_imgs/'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='image',
            field=models.ImageField(null=True, upload_to='documentation_imgs/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(null=True, upload_to='instructor_imgs/'),
        ),
    ]
