# Generated by Django 4.2.5 on 2024-05-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0025_alter_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cellphone',
            new_name='mobile',
        ),
    ]
