# Generated by Django 4.2.5 on 2024-06-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0026_rename_cellphone_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
